apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: photos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:release
          env:
            - name: DB_HOSTNAME
              value: immich-postgres
            - name: DB_DATABASE_NAME
              value: immich
            - name: DB_USERNAME
              value: immich
            - name: DB_PASSWORD
              value: immich
            - name: REDIS_HOSTNAME
              value: immich-redis
          volumeMounts:
            - name: photos
              mountPath: /usr/src/app/upload
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 1000m
          ports:
            - containerPort: 2283
      volumes:
        - name: photos
          persistentVolumeClaim:
            claimName: pvc-immich-photos
---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: photos
spec:
  type: NodePort
  selector:
    app: immich-server
  ports:
    - port: 2283
      targetPort: 2283
      nodePort: 30283
