apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich-redis
  namespace: photos
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
