apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich-photos
  namespace: photos
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1500Gi
  volumeName: pv-immich
